### ISSUE TITLE
[BUG] Crash on calling `border_style`.

### ISSUE THREAD

**Issue by Magicloud** [plotters-rs/plotters#479] opened 2023-06-09 16:06 UTC
**Describe the bug**
I have the code to draw a line chart. There was this line of code, if I commented it out, all went fine. Enabling it would cause the process crashing. The line is:

```
    cc.configure_series_labels()
        .border_style(BLACK)
        .draw()?;
```

**To Reproduce**
```
    let x_range = 0_usize..1000;

    let root_area = BitMapBackend::new(&chart_name, (1024, 768)).into_drawing_area();
    root_area.fill(&WHITE)?;
    let root_area = root_area.titled("Maintitle", ("sans-serif", 60))?;

    let mut cc = ChartBuilder::on(&root_area)
        .margin(5)
        .set_all_label_area_size(50)
        .caption("Subtitle", ("sans-serif", 40))
        .build_cartesian_2d(x_range, 0_f64..3600.0)?;
    cc.configure_mesh()
        .x_labels(20)
        .y_labels(10)
        .disable_mesh()
        .x_label_formatter(&|v| format!("{:.1}", v))
        .y_label_formatter(&|v| format!("{:.1}", v))
        .draw()?;

    input.into_iter().enumerate().try_for_each(|(c, (k, vs))| {
        eprintln!("{vs:?}");
        cc.draw_series(LineSeries::new(vs.into_iter().enumerate(), &COLORS[c]))
            .map(move |x| {
                x.label(k)
                    .legend(move |(x, y)| PathElement::new(vec![(x, y), (x + 20, y)], COLORS[c]));
            })
    })?;

    // cc.configure_series_labels()
    //     .border_style(BLACK)
    //     .draw()?;

    root_area.present()?;
```

**Version Information**

Plotters: v0.3.4
Rust: stable channel, x86_64-unknown-linux-musl target.

**Crashing log**

```
thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x7ff4c4204002', /home/shida/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-bitmap-0.3.2/src/bitmap_pixel/rgb.rs:215:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
   0:     0x55e208e0800a - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e208e0800a - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e208e0800a - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55e208e0800a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55e208e2bf2f - core::fmt::write::h9ffde816c577717b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x55e208e04da5 - std::io::Write::write_fmt::h88186074961638e4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x55e208e07dd5 - std::sys_common::backtrace::_print::h184198273ed08d59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55e208e07dd5 - std::sys_common::backtrace::print::h1b4d8e7add699453
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55e208e0947e - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x55e208e09225 - std::panicking::default_hook::h48c64f31d8b3fd03
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x55e208e099de - std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x55e208e09892 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:580:13
  12:     0x55e208e08476 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x55e208e09632 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     0x55e2086bacc3 - core::panicking::panic_nounwind_fmt::hd4fea0bcbbc9daea
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:96:14
  15:     0x55e2086bad71 - core::panicking::panic_nounwind::h07db722b03cd9dbd
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:126:5
  16:     0x55e2086baf03 - core::panicking::panic_cannot_unwind::hfaa00866a3a05433
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:188:5
  17:     0x55e208d1a1aa - <plotters_bitmap::bitmap_pixel::rgb::RGBPixel as plotters_bitmap::bitmap_pixel::pixel_format::PixelFormat>::fill_rect_fast::h0fedc9ed4820948c
                               at /home/shida/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-bitmap-0.3.2/src/bitmap_pixel/rgb.rs:139:5
  18:     0x55e20871090a - <plotters_bitmap::bitmap::BitMapBackend<P> as plotters_backend::DrawingBackend>::draw_line::hd7e2dc4ccbbaa5b9
                               at /home/shida/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-bitmap-0.3.2/src/bitmap.rs:259:21
  19:     0x55e208711bdf - plotters_backend::DrawingBackend::draw_path::ha011af778483ba77
                               at /home/shida/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-backend-0.3.4/src/lib.rs:176:34
  20:     0x55e2086fa861 - <plotters::element::basic_shapes::PathElement<Coord> as plotters::element::Drawable<DB>>::draw::hde4daecaa967ea32
                               at /home/shida/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/element/basic_shapes.rs:108:9
  21:     0x55e2086faa15 - <T as plotters::element::dynelem::DynDrawable<DB>>::draw_dyn::h10d6ff1a1fae0f50
                               at /home/shida/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/element/dynelem.rs:22:9
  22:     0x55e208702066 - <plotters::element::dynelem::DynElement<DB,Coord> as plotters::element::Drawable<DB>>::draw::h80a162ba5bfb0541
                               at /home/shida/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/element/dynelem.rs:53:9
  23:     0x55e208716a70 - plotters::drawing::area::DrawingArea<DB,CT>::draw::{{closure}}::h5d17da30335cfc2b
                               at /home/shida/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/drawing/area.rs:328:35
  24:     0x55e208715716 - plotters::drawing::area::DrawingArea<DB,CT>::backend_ops::haea2887158f196d9
                               at /home/shida/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/drawing/area.rs:284:13
  25:     0x55e208716874 - plotters::drawing::area::DrawingArea<DB,CT>::draw::hf49eefc9e8e60b62
                               at /home/shida/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/drawing/area.rs:328:9
  26:     0x55e2087265ba - plotters::chart::series::SeriesLabelStyle<DB,CT>::draw::h444463039ac88bcd
                               at /home/shida/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/chart/series.rs:296:13
  27:     0x55e2086dd6c3 - debug_chart::main::hd44c35044dab97f6
                               at /home/shida/src/Work/fpco/debug_chart/src/main.rs:104:5
  28:     0x55e2086e7b2b - core::ops::function::FnOnce::call_once::hd4d3bd8eebdb3112
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  29:     0x55e2087012be - std::sys_common::backtrace::__rust_begin_short_backtrace::h5d6f33a7f5597d6c
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
  30:     0x55e2086f9a71 - std::rt::lang_start::{{closure}}::heef6830840932ca7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:166:18
  31:     0x55e208e00dae - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1327dc2ef3fecdf
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
  32:     0x55e208e00dae - std::panicking::try::do_call::h4044173225fe83dd
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  33:     0x55e208e00dae - std::panicking::try::hd8a722c09d156a53
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  34:     0x55e208e00dae - std::panic::catch_unwind::hd2ca07971cf0119b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  35:     0x55e208e00dae - std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
  36:     0x55e208e00dae - std::panicking::try::do_call::hf47aa1aa005e5f1a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  37:     0x55e208e00dae - std::panicking::try::h73d246b2423eaf4e
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  38:     0x55e208e00dae - std::panic::catch_unwind::hbaaeae8f1b2f9915
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  39:     0x55e208e00dae - std::rt::lang_start_internal::h76f3e81e6b8f13f9
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  40:     0x55e2086f9a4a - std::rt::lang_start::h79777b9b0d6547e9
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:165:17
  41:     0x55e2086dda6e - main
  42:     0x7ff4c4c02850 - <unknown>
  43:     0x7ff4c4c0290a - __libc_start_main
  44:     0x55e2086bb405 - _start
  45:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
[1]    1039231 IOT instruction (core dumped)
```

**Comment by AaronErhardt** [comment] 2023-06-09 22:31
I'm closing this as duplicate of #461

Sorry for the inconvenient situation, see #453 for more information.

**Closed by AaronErhardt** 2023-06-09 22:31 UTC
Labels: bug
