### ISSUE TITLE
[BUG] New lines don't show up in axes labels (x_label_formatter)

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [plotters-rs/plotters#353] opened 2022-05-14 19:49 UTC
**Describe the bug**
When I format with \n or use literals with a new line, I expect to see the new line in the plot text.

New lines are important to be able to put more ticks on the graph that uses dates. Otherwise the x-axis labels easily gets cluttered, and y-axis becomes too wide.

**To Reproduce**
Try to add a new line here in the formatter. It'll be ignored: https://github.com/plotters-rs/plotters/blob/f9985dbc47e047290da7693609ccd3e966eeaa68/examples/chart.rs#L25

**Version Information**
Rust's crates.io's version 0.3.1

**Comment by facorread** [comment] 2022-06-06 22:35
Duplicate of #113

**Closed** 2022-06-23 01:03 UTC
Labels: bug, text rendering
