### ISSUE TITLE
[BUG] Axis bounding box corners don't completely close

### ISSUE THREAD

**Issue by TomDeRybel** [plotters-rs/plotters#349] opened 2022-05-06 08:22 UTC
**Describe the bug**
The corners on the frame that bounds the plotting area don't quite close at the corners. This is a minor issue, it just looks a little off.

**To Reproduce**
Draw axis with some width and observe the corners. The included example demonstrates this issue.

**Version Information**
Using the git version, and fltk 1.3.6

![Screenshot_20220506_101251_annotated](https://user-images.githubusercontent.com/67321804/167094809-80f638c5-fd64-4cb4-87f5-9466a3380483.png)

[plotters_doodle.zip](https://github.com/plotters-rs/plotters/files/8638571/plotters_doodle.zip)

**Comment by facorread** [comment] 2022-06-06 22:45
Duplicate of #165

**Closed** 2022-06-23 01:04 UTC
Labels: bug
