### ISSUE TITLE
[Feature Request] FontTransform doesn't support arbitrary angles

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [plotters-rs/plotters#355] opened 2022-05-16 10:25 UTC
### What is the feature ?
The current `FontTransform` enum supports only rotations of 0, 90, 180 and 270. it has to support an arbitrary floating point angle.

**Comment by facorread** [comment] 2022-06-06 22:38
Duplicate of #231

**Closed** 2022-06-23 01:02 UTC
Labels: enhancement, help wanted, feature request
