### ISSUE TITLE
Failed to download `plotters v0.3.1`

### ISSUE THREAD

**Issue by lunn06** [plotters-rs/plotters#327] opened 2022-01-26 12:20 UTC
When trying `cargo build` with `plotters="0.3.1"` in Cargo.toml it's printing:

failed to download `plotters v0.3.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to unpack package `plotters v0.3.1`

Caused by:
  failed to unpack entry at `plotters-0.3.1/plotters-doc-data/3d-plot2.gif`

Caused by:
  failed to unpack `/home/lun/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.1/plotters-doc-data/3d-plot2.gif`

Caused by:
  failed to unpack `plotters-0.3.1/plotters-doc-data/3d-plot2.gif` into `/home/lun/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.1/plotters-doc-data/3d-plot2.gif`

Caused by:
  unexpected end of file

**BUT!**
When I tryed build with `plotters = { git = "https://github.com/38/plotters.git" }`  building is successfull.

**Version Information**
cargo version is "1.58.0"
rustc version is "1.58.1"

**Comment by 38** [comment] 2022-05-04 23:06
Can't reproduce this. Closing for now, if the problem is still there on your side, feel free to reopen it. Thanks!

**Closed by 38** 2022-05-04 23:06 UTC
Labels: bug
