### ISSUE TITLE
[BUG] Crash with unaligned read in `plotters-bitmap`

### ISSUE THREAD

**Issue by virtualritz** [plotters-rs/plotters#478] opened 2023-06-08 21:09 UTC
**Describe the bug**

I'm trying to run the [`example/plotters.rs`](https://github.com/dorianprill/stroke/blob/main/examples/plotters.rs) from the [`stroke` crate](https://crates.io/crates/stroke). This crashes because of the `unaligned_read()` in [`plotters-bitmap/src/bitmap_pixel/rgb.rs:98`](https://github.com/plotters-rs/plotters/blob/5180b4e9f4de89e5964dc82d8f67ce065b35b6cc/plotters-bitmap/src/bitmap_pixel/rgb.rs#L98).

Specifically:
```
thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x7f26ab1ee279', /home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-bitmap-0.3.2/src/bitmap_pixel/rgb.rs:98:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
   0:     0x55b6725389a1 - trace
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55b6725389a1 - trace_unsynchronized<std::sys_common::backtrace::_print_fmt::{closure_env#1}>
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b6725389a1 - _print_fmt
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55b6725389a1 - fmt
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55b67255ac6f - fmt
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/core/src/fmt/rt.rs:138:9
   5:     0x55b67255ac6f - write
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/core/src/fmt/mod.rs:1094:21
   6:     0x55b672536641 - write_fmt<std::sys::unix::stdio::Stderr>
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/io/mod.rs:1713:15
   7:     0x55b6725387b5 - _print
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55b6725387b5 - print
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55b672539b37 - {closure#1}
  10:     0x55b672539924 - default_hook
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/panicking.rs:288:9
  11:     0x55b67253a05c - rust_panic_with_hook
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/panicking.rs:705:13
  12:     0x55b672539f11 - {closure#0}
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/panicking.rs:595:13
  13:     0x55b672538dd6 - __rust_end_short_backtrace<std::panicking::begin_panic_handler::{closure_env#0}, !>
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55b672539ca2 - begin_panic_handler
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/panicking.rs:593:5
  15:     0x55b672559103 - panic_nounwind_fmt
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/core/src/panicking.rs:96:14
  16:     0x55b6725591a7 - panic_nounwind
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/core/src/panicking.rs:126:5
  17:     0x55b672559333 - core::panicking::panic_cannot_unwind::h12d7723a86019a54
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/core/src/panicking.rs:188:5
  18:     0x55b67246880b - <plotters_bitmap::bitmap_pixel::rgb::RGBPixel as plotters_bitmap::bitmap_pixel::pixel_format::PixelFormat>::blend_rect_fast::h39227128cddaf4cf
                               at /home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-bitmap-0.3.2/src/bitmap_pixel/rgb.rs:33:5
  19:     0x55b6723d47ae - <plotters_bitmap::bitmap::BitMapBackend<P> as plotters_backend::DrawingBackend>::draw_line::h072373a9fdbad0a0
                               at /home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-bitmap-0.3.2/src/bitmap.rs:264:17
  20:     0x55b6723cf1f7 - plotters::coord::ranged2d::cartesian::MeshLine<X,Y>::draw::h2b64841255b4d211
                               at /home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/coord/ranged2d/cartesian.rs:152:9
  21:     0x55b6723e0b28 - plotters::chart::context::cartesian2d::draw_impl::<impl plotters::chart::context::ChartContext<DB,plotters::coord::ranged2d::cartesian::Cartesian2d<X,Y>>>::draw_mesh_lines::{{closure}}::h2ddbb070b50c9dfc
                               at /home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/chart/context/cartesian2d/draw_impl.rs:53:21
  22:     0x55b6723ef678 - plotters::drawing::area::DrawingArea<DB,plotters::coord::ranged2d::cartesian::Cartesian2d<X,Y>>::draw_mesh::{{closure}}::{{closure}}::h3ee2daed6d5483a4
                               at /home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/drawing/area.rs:204:61
  23:     0x55b6723d00f2 - plotters::coord::ranged2d::cartesian::Cartesian2d<X,Y>::draw_mesh::h9fa0bde5dcb5c3cf
                               at /home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/coord/ranged2d/cartesian.rs:72:13
  24:     0x55b6723ef587 - plotters::drawing::area::DrawingArea<DB,plotters::coord::ranged2d::cartesian::Cartesian2d<X,Y>>::draw_mesh::{{closure}}::h3b3b11d6faa2a9b6
                               at /home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/drawing/area.rs:203:13
  25:     0x55b6723e9f16 - plotters::drawing::area::DrawingArea<DB,CT>::backend_ops::h06c8362bd577451c
                               at /home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/drawing/area.rs:284:13
  26:     0x55b6723ef499 - plotters::drawing::area::DrawingArea<DB,plotters::coord::ranged2d::cartesian::Cartesian2d<X,Y>>::draw_mesh::h3ed1859a54b1fa74
                               at /home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/drawing/area.rs:202:9
  27:     0x55b6723c99ed - plotters::chart::context::cartesian2d::draw_impl::<impl plotters::chart::context::ChartContext<DB,plotters::coord::ranged2d::cartesian::Cartesian2d<X,Y>>>::draw_mesh_lines::h8e425618f7860a88
                               at /home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/chart/context/cartesian2d/draw_impl.rs:36:9
  28:     0x55b6723cdebc - plotters::chart::context::cartesian2d::draw_impl::<impl plotters::chart::context::ChartContext<DB,plotters::coord::ranged2d::cartesian::Cartesian2d<X,Y>>>::draw_mesh::hf273867f231fda8e
                               at /home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/chart/context/cartesian2d/draw_impl.rs:344:13
  29:     0x55b672408a8e - plotters::chart::mesh::MeshStyle<X,Y,DB>::draw::h88002ddece084cd2
                               at /home/moritz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.4/src/chart/mesh.rs:467:9
  30:     0x55b6723dd441 - plotters::main::h55dfab7e77ff95bf
                               at /home/moritz/code/crates/stroke/examples/plotters.rs:63:5
  31:     0x55b6723c5beb - core::ops::function::FnOnce::call_once::hf56ddc9d459ed6e2
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/core/src/ops/function.rs:250:5
  32:     0x55b672402aee - std::sys_common::backtrace::__rust_begin_short_backtrace::ha78ff293ed8734e4
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/sys_common/backtrace.rs:135:18
  33:     0x55b6723defa1 - std::rt::lang_start::{{closure}}::h330d6f5be1d540b2
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/rt.rs:166:18
  34:     0x55b672532fd5 - call_once<(), (dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)>
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/core/src/ops/function.rs:284:13
  35:     0x55b672532fd5 - do_call<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32>
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/panicking.rs:500:40
  36:     0x55b672532fd5 - try<i32, &(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)>
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/panicking.rs:464:19
  37:     0x55b672532fd5 - catch_unwind<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32>
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/panic.rs:142:14
  38:     0x55b672532fd5 - {closure#2}
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/rt.rs:148:48
  39:     0x55b672532fd5 - do_call<std::rt::lang_start_internal::{closure_env#2}, isize>
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/panicking.rs:500:40
  40:     0x55b672532fd5 - try<isize, std::rt::lang_start_internal::{closure_env#2}>
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/panicking.rs:464:19
  41:     0x55b672532fd5 - catch_unwind<std::rt::lang_start_internal::{closure_env#2}, isize>
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/panic.rs:142:14
  42:     0x55b672532fd5 - lang_start_internal
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/rt.rs:148:20
  43:     0x55b6723def7a - std::rt::lang_start::he38ff1c913c1507a
                               at /rustc/e6d4725c76f3b526c74454bc51afdf6daf133506/library/std/src/rt.rs:165:17
  44:     0x55b6723de0ce - main
  45:     0x7f26ab223a90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  46:     0x7f26ab223b49 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  47:     0x55b6723a5355 - _start
  48:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
```

**To Reproduce**

```
git clone https://github.com/dorianprill/stroke.git
rustup override set nightly
cargo run --example plotters
```

**Version Information**

I tried with `plotters 0.3.0` as well as `0.3.4`.

I am on Ubuntu 23.04 using `rust-1.72.0-nightly (a97c36dd2 2023-06-07)`.

**Comment by jscatena88** [comment] 2023-06-09 04:07
The `unaligned_read()` actually fixes this crash. I am running into an almost identical issue except in a different line of the file. It seems those fixes were added to address these crashes on 4/20/23: https://github.com/plotters-rs/plotters/commits/master/plotters-bitmap/src/bitmap_pixel/rgb.rs

However the latest release on crates.io is from 9 months ago. 

Would it be possible to get a new release pushed up to crates.io?

In the meantime @virtualritz you can get around this by patching your cargo.toml to use the github copy of the crate by adding this to the bottom:

```
[patch.crates-io]
plotters = { git = "https://github.com/plotters-rs/plotters.git" }
```

Also make sure that you use this version notation in your `[dependencies]` section: `plotters = "^0.3.4"` to indicate that you are ok with using the version 0.3.5 that is defined as the version number of this crate on github

**Comment by AaronErhardt** [comment] 2023-06-09 08:22
I'm closing this as a duplicate of #461

Regarding the new release, there's already this issue: #453

**Closed by AaronErhardt** 2023-06-09 08:22 UTC
Labels: bug
