### ISSUE TITLE
[Bug] Top axis label dropped incorrectly

### ISSUE THREAD

**Issue by arctic-alpaca** [plotters-rs/plotters#186] opened 2020-09-10 11:28 UTC
Hello,
I couldn't find a way to draw the top most label on the y axis.
The `.with_key_points` method seems to ignore the top most label.
When using 
```
.build_cartesian_2d(
    (0u32..10u32).into_segmented(),
    (0u32..10u32).with_key_points(vec![0, 1, 2, 3, 4, 6, 7, 8, 9, 10]),
)
```
in the [histogram example ](https://github.com/38/plotters/blob/master/examples/histogram.rs), 10 still doesn't get printed on the y axis.
Is this a current limitation of the library or did I miss something?

**Comment by 38** [comment] 2020-09-10 14:34
Hi, thanks for reporting this. I've looked into it, I feel this is a bug which caused by a 1px offset of plotting area. 
This is most likely link to #165 

The reason why this is happening is Plotters actually checks if the label is out of change of the subplot https://github.com/38/plotters/blob/master/src/chart/context.rs#L331

But at this point, the relative position is -1 (which should be 0) that causes Plotters drop the top label - but previously I haven't realize this is actually a bug.

Thanks again for reporting this!

**Comment by 38** [comment] 2022-06-26 01:16
Hi there, just verified this is fixed by the commit I pushed. Close the issue for now.

**Closed by 38** 2022-06-26 01:16 UTC
Labels: bug

**Comment by wangjiawen2013** [comment] 2024-02-20 03:09
I tried this method and find that it worked for integer coord, but didn't work for f64 coord. The error occured:
![image](https://github.com/plotters-rs/plotters/assets/29703450/1a0fed69-deff-41f1-90ac-214f118f7da4)

The following is the code I used:
```
evcxr_figure((640, 240), |root| {
    let mut chart = ChartBuilder::on(&root).x_label_area_size(40).y_label_area_size(40)
   .build_cartesian_2d(
       (0.0..100.0).with_key_points(vec![-5.0, 0.0, 10.0,20.0,50.0,90.0]),   // <= This line will make the plot shows 4 tick marks at 1, 20, 50, 90
       0..10
    ).unwrap();
    chart.configure_mesh()
        .x_desc("X")
        .y_desc("Y")
        .y_labels(10)
        .light_line_style(&TRANSPARENT)
        .label_style(("sans-serif", 15, &BLACK).into_text_style(&root))  // 坐标标签属性
        //.x_label_formatter(&|v| format!("{:.1}", v))
        //.y_label_formatter(&|v| format!("{:.1}", v))
        .disable_x_mesh()
        .draw().unwrap();
    Ok(())
}).style("width:60%")
```
